### ISSUE TITLE
Compat with `go install`

### ISSUE THREAD

**Issue by mitranim** [AntonioSun/xmlfmt#1]
Would be nice if one could `go install github.com/AntonioSun/xmlfmt@latest` without manually fiddling with executables. Currently it fails with dependency-related errors. Would you consider fixing it?

**Comment by AntonioSun** [comment]
Hmm... I never used or experienced `go install` before. In order to reply to your question, I did a bit reading, and according to [here](https://stackoverflow.com/questions/24069664/what-does-go-install-do),

> `go install` does a little bit more. It moves the executable file to
> `$GOPATH/bin` and caches all non-main packages which are imported to
> `$GOPATH/pkg`. The cache will be used during the next compilation provided the 
> source did not change yet.

If that's still the case, and by `dependency` you meant the go packages that this tool depends on, then I'm afraid that this is a Go tooling issue that beyond my power and fix. If you have a solution, please submit a PR.

That being said, 

- If you want to use source, then `go get -v -u ./...` will fix any dependency-related errors by installing the go packages that this tool depends on.
- If you just need the binary, then head to https://github.com/AntonioSun/xmlfmt/releases/latest and the pre-built binaries or packages are already there.

**Comment by mitranim** [comment]
Just to clear up any potential confusion, let me elaborate. In prior versions of Go, `go get` was used to download dependencies _and_ to install CLI binaries. In current versions, you're supposed to use `go install <pkg>@<ver>` to download, build, _and_ install a CLI binary from source. Kinda like `brew install` or `apk install` but for Go stuff. For users who already have a Go toolchain set up, this is more convenient than manual binary download or repo cloning, and it requires absolutely no setup from the author. For example, both my https://github.com/mitranim/gow and https://github.com/mitranim/jsonfmt are installed this way ; justified in case of `gow` since it's a development tool for Go users.

For example, if the `xmlfmt` CLI was simply the following:

```go
package main

import (
	"io"
	"os"

	"github.com/go-xmlfmt/xmlfmt"
)

func main() {
	src, err := io.ReadAll(os.Stdin)
	if err != nil {
		panic(err)
	}

	io.WriteString(os.Stdout, xmlfmt.FormatXML(string(src), ``, `  `))
}
```

...then one could `go install` as in my original post, to 1-command install or update it. Anyway the above is what I've setup for my personal use and it works.

The errors I got seemed fixable, something about one of the dependencies self-declaring its package name/address differently from how it's imported... Anyway I'm just throwing this out here. You could try fixing it, or not. 🙂

**Comment by AntonioSun** [comment]
Oh, thanks for the explanation. 

Seems I got some more reading to do. Thanks for providing a working example, as it always hard in situations that things are not working in the first place. . . 

I'll look into it in a few weeks. thx again.

**Comment by AntonioSun** [comment]
Fixed. Let me know otherwise.
